(define-module (yellowsquid packages rust-apps)
  #:use-module (gnu packages crates-io)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages tls)
  #:use-module (guix build-system cargo)
  #:use-module (guix download)
  #:use-module (guix git-download)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages)
  #:use-module (yellowsquid packages crates-io))

(define-public spotifyd
  (package
    (name "spotifyd")
    (version "0.3.3")
    (home-page "https://github.com/Spotifyd/spotifyd")
    (source
      (origin
        (method git-fetch)
        (uri (git-reference
              (url home-page)
              (commit (string-append "v" version))))
        (file-name (git-file-name name version))
        (sha256
          (base32 "1liql2wp7cx0x4ha1578wx3m4byd295m4ph268s05yw2wrnr3v6c"))))
    (build-system cargo-build-system)
    (inputs (list alsa-lib dbus openssl pulseaudio))
    (native-inputs (list pkg-config))
    (arguments
      `(#:cargo-inputs
        (("rust-alsa" ,rust-alsa-0.5)
         ("rust-chrono" ,rust-chrono-0.4)
         ("rust-color-eyre" ,rust-color-eyre-0.5)
         ("rust-daemonize" ,rust-daemonize-0.4)
         ("rust-dbus" ,rust-dbus-0.9)
         ("rust-dbus-crossroads" ,rust-dbus-crossroads-0.4)
         ("rust-dbus-tokio" ,rust-dbus-tokio-0.7)
         ("rust-fern" ,rust-fern-0.6)
         ("rust-futures" ,rust-futures-0.3.15)
         ("rust-gethostname" ,rust-gethostname-0.2)
         ("rust-hex" ,rust-hex-0.4)
         ("rust-keyring" ,rust-keyring-0.10)
         ("rust-libc" ,rust-libc-0.2)
         ("rust-librespot-audio" ,rust-librespot-audio-0.2)
         ("rust-librespot-connect" ,rust-librespot-connect-0.2)
         ("rust-librespot-core" ,rust-librespot-core-0.2)
         ("rust-librespot-playback" ,rust-librespot-playback-0.2)
         ("rust-log" ,rust-log-0.4)
         ("rust-percent-encoding" ,rust-percent-encoding-2)
         ("rust-reqwest" ,rust-reqwest-0.11)
         ("rust-rspotify" ,rust-rspotify-0.8)
         ("rust-serde" ,rust-serde-1)
         ("rust-sha-1" ,rust-sha-1-0.9)
         ("rust-structopt" ,rust-structopt-0.3)
         ("rust-syslog" ,rust-syslog-4)
         ("rust-tokio" ,rust-tokio-1.6)
         ("rust-tokio-compat" ,rust-tokio-compat-0.1)
         ("rust-tokio-compat-02" ,rust-tokio-compat-02-0.2)
         ("rust-tokio-stream" ,rust-tokio-stream-0.1.7)
         ("rust-url" ,rust-url-1)
         ("rust-whoami" ,rust-whoami-0.9)
         ("rust-xdg" ,rust-xdg-2))
        #:cargo-development-inputs
        (("rust-env-logger" ,rust-env-logger-0.7))
        #:features
        '("pulseaudio_backend" "dbus_keyring" "dbus_mpris")))
    (synopsis "A Spotify daemon")
    (description "This package provides a Spotify daemon")
    (license license:gpl3)))
